#!/usr/bin/env bash
# OC Order Management

usage () {
    cat <<HELP_USAGE
    payment (usage|host) [token] [get|create|trx] [params]
    examples for oc-cli command list file:
        payment create ORDER_ID payment_sa.json
        payment trx ORDER_ID PAYMENT_ID payment_transaction1.json
        payment get ORDER_ID
        payment get ORDER_ID PAYMENT_ID
HELP_USAGE
}

if [[ ($1) && $1 == "usage" ]]; then
    usage
    exit 255
fi
if [[ (-z "$2") ]]; then
    sh cmds/errors/generic
    exit $?
fi


if [ $3 == "get" ]; then
    curl -w "%{http_code}:%{time_total}s\n" -s -o logs/$4.payments$5.get.json https://$1/v1/orders/Outgoing/$4/payments/$5 -X GET -H "Content-Type: application/json;" -H  "Authorization: Bearer "$2
fi
if [ $3 == "create" ]; then
    filename=${5##*/}
    curl -isf -w "%{http_code}:%{time_total}s\n" -o logs/$filename.log https://$1/v1/orders/Outgoing/$4/payments -X POST -H "Content-Type: application/json;" -H  "Authorization: Bearer "$2 -d @$5
fi
if [ $3 == "trx" ]; then
    filename=${6##*/}
    curl -isf -w "%{http_code}:%{time_total}s\n" -o logs/$filename.log https://$1/v1/orders/Outgoing/$4/payments/$5/transactions -X POST -H "Content-Type: application/json;" -H  "Authorization: Bearer "$2 -d @$6
fi
 
